### ISSUE TITLE
Buttons and Doors Don't Work

### ISSUE THREAD

**Issue by k8wu** [yquake2/slightmechanicaldestruction#4]
I discovered that doors and buttons do not work, which effectively stops the game at the bridge control room in the Control Center Hub map. I thought about doing a +use while standing in front of it, as there is a viewscreen that uses +use for its functionality, but that does not work, either. I have no way forward without it.

I noclip'ed through the nearby door which does not open for me (is it supposed to?), and the buttons and doors on the other side of that door do not operate, either.

**Comment by emileb** [comment]
Caused by this regression: https://github.com/yquake2/slightmechanicaldestruction/commit/29df38f23955219026b286fb479dc90a506aa535#r70282792
